image: xebiafrance/serverless-node

stages:
  - build
  - dev
  - prod

before_script:
  - cd extremStartup
  - npm install

test_local:
  stage: build
  script:
    - npm run testLocal

deploy_dev:
  stage: dev
  script:
    - npm run buildDev
    - npm run testDev

deploy_prod:
  stage: prod
  script:
    - npm run buildProd
  when: manual