service: extremStartup

# frameworkVersion: "=X.X.X"

provider:
  name: aws
  runtime: nodejs6.10

  stage: dev
  region: eu-west-1

  environment:
    stage: ${opt:stage, self:provider.stage}
    region: ${opt:region, self:provider.region}
    base_sns:
      Fn::Join:
        - ":"
        - - arn
          - aws
          - sns
          - Ref: AWS::Region
          - Ref: AWS::AccountId
    topic_sns: ${self:provider.environment.stage}-checkAnswer
    test_bucket: ${self:provider.environment.stage}-check-answer
    base_url: http://ecs-first-run-alb-1315137913.eu-west-1.elb.amazonaws.com/players/
    player_id: 1e0e0bc0

  iamRoleStatements:
    - Effect: "Allow"
      Resource: "arn:aws:sns:*:*:${self:provider.environment.topic_sns}"
      Action:
        - "sns:*"
    - Effect: "Allow"
      Resource: "arn:aws:s3:::${self:provider.environment.test_bucket}/*"
      Action:
        - "s3:*"
    - Effect: "Allow"
      Resource: "arn:aws:s3:::${self:provider.environment.test_bucket}"
      Action:
        - "s3:*"

functions:
  answer:
    handler: answer.receiveQuestion
    tags:
      owner: plopez
    events:
      - http:
          path: /
          method: get
          integration: lambda

  check:
      handler: answer.checkResult
      tags:
        owner: plopez
      events:
        - sns: ${self:provider.environment.topic_sns}

resources:
  Resources:
    unitTestBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:provider.environment.stage}-check-answer
